name: Rust MacOS Release

on:
  push:
    tags:
      - 'v*'
  create:
    tags:
      - 'v*'

jobs:
  release-macos:
    name: release-macos
    runs-on: macos-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: test 
        run: cargo test
      - name: compile
        env:
          RUSTFLAGS: "-D warnings" # Disallow warnings
        run: cargo build --release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
            #automatic_release_tag: latest-macos
          files: |
            target/release/automattermostatus
      - name: upload to gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: 'curl --fail-with-body --user ignored:$GITLAB_TOKEN --upload-file target/release/automattermostatus https://gitlab.com/api/v4/projects/30645379/packages/generic/binaries/v0.1.2/automattermostatus-macos-amd64'



