name: Rust  Release

on:
  push:
    tags:
      - 'v*'
  create:
    tags:
      - 'v*'

jobs:
  release-macos:
    name: release-macos
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: test 
        run: cargo test
      - name: compile
        env:
          RUSTFLAGS: "-D warnings" # Disallow warnings
        run: cargo build --release
      - name: upload to gitlab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          OS: ${{ matrix.os }}
        run: |
          if [[ $OS == macOS-latest ]]  then 'curl --fail-with-body --user ignored:$GITLAB_TOKEN --upload-file target/release/automattermostatus https://gitlab.com/api/v4/projects/30645379/packages/generic/binaries/v0.1.2/automattermostatus-macos-amd64' ; else  true; fi
          if [[ $OS == ubuntu-latest ]]  then 'curl --fail-with-body --user ignored:$GITLAB_TOKEN --upload-file target/release/automattermostatus https://gitlab.com/api/v4/projects/30645379/packages/generic/binaries/v0.1.2/automattermostatus-linux-amd64' ; else  true; fi
          if [[ $OS == windows-latest ]]  then 'curl --fail-with-body --user ignored:$GITLAB_TOKEN --upload-file target/release/automattermostatus.exe https://gitlab.com/api/v4/projects/30645379/packages/generic/binaries/v0.1.2/automattermostatus-windows-amd64.exe' ; else  true; fi



